apiVersion: v1
kind: Service
metadata:
  name: crop-monitoring-service
spec:
  selector:
    app: crop-monitoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
